In [1]:
import os
import pandas as pd
import  numpy as np
import matplotlib as plt
%matplotlib inline
import warnings
warnings.simplefilter("ignore")

In [2]:
Train = pd.read_csv("Train.csv")
Test  = pd.read_csv("Test.csv")
sub= pd.read_csv("SampleSubmission.csv")

In [3]:
Train.head()

,ID,country,year,urban_or_rural,ghsl_water_surface,ghsl_built_pre_1975,ghsl_built_1975_to_1990,ghsl_built_1990_to_2000,ghsl_built_2000_to_2014,ghsl_not_built_up,ghsl_pop_density,landcover_crops_fraction,landcover_urban_fraction,landcover_water_permanent_10km_fraction,landcover_water_seasonal_10km_fraction,nighttime_lights,dist_to_capital,dist_to_shoreline,Target
0,ID_AAIethGy,Ethiopia,2016,R,0.0,0.000000,0.000000,0.000055,0.000536,0.999408,12.146134,25.489659,0.879484,0.000000,0.000000,0.000000,278.788451,769.338378,0.132783
1,ID_AAYiaCeL,Ethiopia,2005,R,0.0,0.000000,0.000110,0.000000,0.000018,0.999872,113.806716,64.136053,0.601427,0.000000,0.005427,0.000000,200.986978,337.135243,0.004898
2,ID_AAdurmKj,Mozambique,2009,R,0.0,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,4.400096,0.131900,0.000000,0.003078,0.000000,642.594208,169.913773,0.097320
3,ID_AAgNHles,Malawi,2015,R,0.0,0.000141,0.000181,0.000254,0.000228,0.999195,5.213320,25.379371,2.017136,11.293841,0.131035,0.000000,365.349451,613.591610,0.304107
4,ID_AAishfND,Guinea,2012,U,0.0,0.011649,0.017560,0.017383,0.099875,0.853533,31.734661,5.081620,22.815984,0.005047,0.130475,1.461894,222.867189,192.926363,0.605328

In [4]:
Test.head()

,ID,country,year,urban_or_rural,ghsl_water_surface,ghsl_built_pre_1975,ghsl_built_1975_to_1990,ghsl_built_1990_to_2000,ghsl_built_2000_to_2014,ghsl_not_built_up,ghsl_pop_density,landcover_crops_fraction,landcover_urban_fraction,landcover_water_permanent_10km_fraction,landcover_water_seasonal_10km_fraction,nighttime_lights,dist_to_capital,dist_to_shoreline
0,ID_AAcismbB,Democratic Republic of Congo,2007,R,0.000000,0.000000,0.000000,0.000523,0.000131,0.999347,0.660758,0.990942,0.132264,0.069055,0.032627,0.000000,1249.294720,1364.592100
1,ID_AAeBMsji,Democratic Republic of Congo,2007,U,0.000000,0.004239,0.000238,0.001227,0.002860,0.991437,6.441547,5.461365,0.452400,0.000000,0.000000,0.000000,821.019579,1046.028681
2,ID_AAjFMjzy,Uganda,2011,U,0.007359,0.525682,0.132795,0.095416,0.042375,0.196373,587.516458,2.881811,87.387991,3.248483,3.950374,60.070041,3.620455,906.057334
3,ID_AAmMOEEC,Burkina Faso,2010,U,0.000000,0.000089,0.000036,0.001519,0.001358,0.996997,35.141762,33.878927,4.166437,0.000000,0.130727,1.333999,109.493969,775.139189
4,ID_ABguzDxp,Zambia,2007,R,0.000000,0.000138,0.000623,0.000615,0.002961,0.995663,3.442449,33.491994,3.437129,0.133563,0.128997,0.502203,133.643319,835.591501

In [5]:
Train.describe().T

,count,mean,std,min,25%,50%,75%,max
year,21454.0,2010.060874,4.799579,1994.000000,2008.000000,2011.000000,2014.000000,2016.000000
ghsl_water_surface,21454.0,0.028259,0.097490,0.000000,0.000000,0.000000,0.000000,0.969956
ghsl_built_pre_1975,21454.0,0.038222,0.113562,0.000000,0.000000,0.000198,0.007987,0.877116
ghsl_built_1975_to_1990,21454.0,0.028644,0.077367,0.000000,0.000000,0.000709,0.009868,0.685010
ghsl_built_1990_to_2000,21454.0,0.012689,0.032745,0.000000,0.000043,0.001001,0.008128,0.515534
ghsl_built_2000_to_2014,21454.0,0.018386,0.040421,0.000000,0.000124,0.001871,0.014936,0.649159
ghsl_not_built_up,21454.0,0.873800,0.239294,0.000859,0.897867,0.991919,0.999532,1.000000
ghsl_pop_density,21454.0,95.756775,209.704761,0.000000,3.848533,17.632672,63.225683,1741.256516
landcover_crops_fraction,21454.0,21.034265,16.751106,0.000000,5.610515,18.509291,33.590293,80.064918
landcover_urban_fraction,21454.0,13.999061,23.715485,0.000000,0.798841,2.770159,12.621501,98.784092
landcover_water_permanent_10km_fraction,21454.0,1.486849,6.550171,0.000000,0.000000,0.000516,0.152364,99.164018
landcover_water_seasonal_10km_fraction,21454.0,0.714891,2.383701,0.000000,0.001325,0.029151,0.381969,56.201637
nighttime_lights,21454.0,8.506543,21.090378,0.000000,0.000000,0.137333,4.830194,382.932769
dist_to_capital,21454.0,289.722268,238.811778,0.105306,115.890873,256.736472,401.153071,1897.351575
dist_to_shoreline,21454.0,402.608539,321.517285,0.112080,126.379463,327.271973,643.910675,1769.523906
Target,21454.0,0.350736,0.194376,0.000000,0.195772,0.293574,0.499003,1.000000

In [6]:
Train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21454 entries, 0 to 21453
Data columns (total 19 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   ID                                       21454 non-null  object
 1   country                                  21454 non-null  object
 2   year                                     21454 non-null  int64
 3   urban_or_rural                           21454 non-null  object
 4   ghsl_water_surface                       21454 non-null  float64
 5   ghsl_built_pre_1975                      21454 non-null  float64
 6   ghsl_built_1975_to_1990                  21454 non-null  float64
 7   ghsl_built_1990_to_2000                  21454 non-null  float64
 8   ghsl_built_2000_to_2014                  21454 non-null  float64
 9   ghsl_not_built_up                        21454 non-null  float64
 10  ghsl_pop_density                         21454 non-null  float64
 11  landcover_crops_fraction                 21454 non-null  float64
 12  landcover_urban_fraction                 21454 non-null  float64
 13  landcover_water_permanent_10km_fraction  21454 non-null  float64
 14  landcover_water_seasonal_10km_fraction   21454 non-null  float64
 15  nighttime_lights                         21454 non-null  float64
 16  dist_to_capital                          21454 non-null  float64
 17  dist_to_shoreline                        21454 non-null  float64
 18  Target                                   21454 non-null  float64
dtypes: float64(15), int64(1), object(3)
memory usage: 3.1+ MB

In [7]:
Train.skew().T

year                                      -1.208174
ghsl_water_surface                         4.462055
ghsl_built_pre_1975                        4.060007
ghsl_built_1975_to_1990                    3.829905
ghsl_built_1990_to_2000                    5.544228
ghsl_built_2000_to_2014                    3.985801
ghsl_not_built_up                         -2.134893
ghsl_pop_density                           3.605561
landcover_crops_fraction                   0.562865
landcover_urban_fraction                   2.016126
landcover_water_permanent_10km_fraction    7.653752
landcover_water_seasonal_10km_fraction     8.147797
nighttime_lights                           3.700020
dist_to_capital                            1.971310
dist_to_shoreline                          0.624904
Target                                     0.665610
dtype: float64

In [8]:
Train.isnull().sum().any(),Test.isnull().sum().any()

(False, False)

In [9]:
Train.duplicated().sum().any(),Test.duplicated().sum().any()

(False, False)

In [12]:
# making a copy of Train & Test 
Train.copy(),
Test.copy()

,ID,country,year,urban_or_rural,ghsl_water_surface,ghsl_built_pre_1975,ghsl_built_1975_to_1990,ghsl_built_1990_to_2000,ghsl_built_2000_to_2014,ghsl_not_built_up,ghsl_pop_density,landcover_crops_fraction,landcover_urban_fraction,landcover_water_permanent_10km_fraction,landcover_water_seasonal_10km_fraction,nighttime_lights,dist_to_capital,dist_to_shoreline
0,ID_AAcismbB,Democratic Republic of Congo,2007,R,0.000000,0.000000,0.000000,0.000523,0.000131,0.999347,0.660758,0.990942,0.132264,0.069055,0.032627,0.000000,1249.294720,1364.592100
1,ID_AAeBMsji,Democratic Republic of Congo,2007,U,0.000000,0.004239,0.000238,0.001227,0.002860,0.991437,6.441547,5.461365,0.452400,0.000000,0.000000,0.000000,821.019579,1046.028681
2,ID_AAjFMjzy,Uganda,2011,U,0.007359,0.525682,0.132795,0.095416,0.042375,0.196373,587.516458,2.881811,87.387991,3.248483,3.950374,60.070041,3.620455,906.057334
3,ID_AAmMOEEC,Burkina Faso,2010,U,0.000000,0.000089,0.000036,0.001519,0.001358,0.996997,35.141762,33.878927,4.166437,0.000000,0.130727,1.333999,109.493969,775.139189
4,ID_ABguzDxp,Zambia,2007,R,0.000000,0.000138,0.000623,0.000615,0.002961,0.995663,3.442449,33.491994,3.437129,0.133563,0.128997,0.502203,133.643319,835.591501
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7189,ID_zxzKJCMI,Zimbabwe,2010,R,0.000000,0.000000,0.000000,0.000016,0.000131,0.999853,0.304446,32.263180,0.658724,0.000000,0.077742,0.103892,500.988790,703.139988
7190,ID_zyBrpgRp,Uganda,2011,U,0.000000,0.000056,0.000883,0.003861,0.002483,0.992717,36.160182,27.520555,3.615442,0.000000,0.001157,0.000000,159.587852,1000.194893
7191,ID_zyMafcYq,Burkina Faso,2010,U,0.002683,0.000268,0.002800,0.009322,0.042527,0.942399,46.127465,35.674511,12.705561,0.001129,0.723252,4.734974,33.775441,781.833777
7192,ID_zyfMsHMG,Zimbabwe,2011,R,0.000332,0.000000,0.000017,0.000000,0.000100,0.999551,0.309696,18.050789,0.030514,0.033177,0.222629,0.175123,320.974153,605.920204
7193,ID_zytUOqJv,Democratic Republic of Congo,2007,U,0.076950,0.128367,0.000000,0.041799,0.139710,0.613173,162.182887,3.917284,36.528453,4.499446,0.647506,4.224699,1186.131373,1456.101058

In [14]:
# dropping some columns
X = Train.drop(["ID","Target"], axis=1)
y = Train["Target"]
X_test = Test.drop(["ID"], axis=1)

In [15]:
#ENCODING OF THE CATEGORICAL FEATURES
from sklearn.preprocessing import LabelEncoder

In [16]:
for i in ["country","urban_or_rural"]:
    X[i]= LabelEncoder().fit_transform(X[i])
    X_test[i]=LabelEncoder().fit_transform(X_test[i])

In [17]:
X.head()

,country,year,urban_or_rural,ghsl_water_surface,ghsl_built_pre_1975,ghsl_built_1975_to_1990,ghsl_built_1990_to_2000,ghsl_built_2000_to_2014,ghsl_not_built_up,ghsl_pop_density,landcover_crops_fraction,landcover_urban_fraction,landcover_water_permanent_10km_fraction,landcover_water_seasonal_10km_fraction,nighttime_lights,dist_to_capital,dist_to_shoreline
0,3,2016,0,0.0,0.000000,0.000000,0.000055,0.000536,0.999408,12.146134,25.489659,0.879484,0.000000,0.000000,0.000000,278.788451,769.338378
1,3,2005,0,0.0,0.000000,0.000110,0.000000,0.000018,0.999872,113.806716,64.136053,0.601427,0.000000,0.005427,0.000000,200.986978,337.135243
2,10,2009,0,0.0,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,4.400096,0.131900,0.000000,0.003078,0.000000,642.594208,169.913773
3,8,2015,0,0.0,0.000141,0.000181,0.000254,0.000228,0.999195,5.213320,25.379371,2.017136,11.293841,0.131035,0.000000,365.349451,613.591610
4,5,2012,1,0.0,0.011649,0.017560,0.017383,0.099875,0.853533,31.734661,5.081620,22.815984,0.005047,0.130475,1.461894,222.867189,192.926363

In [18]:
X_test.head()

,country,year,urban_or_rural,ghsl_water_surface,ghsl_built_pre_1975,ghsl_built_1975_to_1990,ghsl_built_1990_to_2000,ghsl_built_2000_to_2014,ghsl_not_built_up,ghsl_pop_density,landcover_crops_fraction,landcover_urban_fraction,landcover_water_permanent_10km_fraction,landcover_water_seasonal_10km_fraction,nighttime_lights,dist_to_capital,dist_to_shoreline
0,3,2007,0,0.000000,0.000000,0.000000,0.000523,0.000131,0.999347,0.660758,0.990942,0.132264,0.069055,0.032627,0.000000,1249.294720,1364.592100
1,3,2007,1,0.000000,0.004239,0.000238,0.001227,0.002860,0.991437,6.441547,5.461365,0.452400,0.000000,0.000000,0.000000,821.019579,1046.028681
2,4,2011,1,0.007359,0.525682,0.132795,0.095416,0.042375,0.196373,587.516458,2.881811,87.387991,3.248483,3.950374,60.070041,3.620455,906.057334
3,2,2010,1,0.000000,0.000089,0.000036,0.001519,0.001358,0.996997,35.141762,33.878927,4.166437,0.000000,0.130727,1.333999,109.493969,775.139189
4,5,2007,0,0.000000,0.000138,0.000623,0.000615,0.002961,0.995663,3.442449,33.491994,3.437129,0.133563,0.128997,0.502203,133.643319,835.591501

In [20]:
# SPILTING DATA INTO TRAIN & VALIDATION SETS
from sklearn.model_selection import train_test_split

X_train, X_val, y_train, y_val = train_test_split(X, y, test_size = 0.2, random_state=1000)

In [37]:
# MODEL BUILDING PART2
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import cross_val_score
from sklearn.metrics import log_loss, accuracy_score
from sklearn.pipeline import Pipeline

In [38]:
pipe = Pipeline([("scaler", StandardScaler()),("model", LinearRegression())])

In [74]:
pipe.fit(X_train,y_train)
pipe.score(X_val, y_val)

0.6260430549010634

In [40]:
pred= pipe.predict(X_val)
pred

array([0.56811269, 0.28104461, 0.53583589, ..., 0.32187297, 0.24855804,
       0.22153743])

In [44]:
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score

In [50]:
kfolds = KFold(n_splits=10, random_state= 1000, shuffle= True)
model = LinearRegression()
scoring = 'neg_mean_absolute_error'
results = cross_val_score(model, X, y, cv=kfolds, scoring=scoring)
results.mean()

-0.0923810716124974

In [52]:
model.fit(X_train, y_train)

LinearRegression()

In [53]:
prediction = model.predict(X_val)
prediction

array([0.57301236, 0.28356338, 0.52913084, ..., 0.31799421, 0.25059067,
       0.22427718])

In [54]:
# making prediction on unseen data (X_test)
#fitting the entire data

model.fit(X, y)

pred = model.predict(X_test)
pred

array([0.04583046, 0.28211585, 0.64174284, ..., 0.4499613 , 0.22728713,
       0.32440291])

# SPOT-CHECKING OF ALGORITHMS

In [57]:
from sklearn.linear_model import Ridge

In [58]:
model2 = Ridge()
scoring = 'neg_mean_absolute_error'
results = cross_val_score(model2, X, y, cv=kfolds, scoring=scoring)
results.mean()

-0.09238267653605887

# Improve Performance with Ensembles

In [61]:
from catboost import CatBoostRegressor

In [73]:
model3 =  CatBoostRegressor(
 iterations=10,
    depth=3,
    learning_rate=0.1,
    loss_function="RMSE"
)
model3.fit(X_train, y_train)
model3.score(X_val, y_val)

0:	learn: 0.1828590	total: 2.63ms	remaining: 23.7ms
1:	learn: 0.1728670	total: 5.27ms	remaining: 21.1ms
2:	learn: 0.1645021	total: 7.7ms	remaining: 18ms
3:	learn: 0.1569455	total: 10.1ms	remaining: 15.1ms
4:	learn: 0.1508491	total: 12.7ms	remaining: 12.7ms
5:	learn: 0.1451692	total: 15.3ms	remaining: 10.2ms
6:	learn: 0.1404320	total: 17.9ms	remaining: 7.65ms
7:	learn: 0.1363278	total: 20.4ms	remaining: 5.11ms
8:	learn: 0.1327467	total: 22.8ms	remaining: 2.53ms
9:	learn: 0.1293115	total: 25.2ms	remaining: 0us

0.5539234595129061

In [64]:
check=model3.predict(X_val)
check

array([0.52020734, 0.2623618 , 0.49329583, ..., 0.39564507, 0.27291311,
       0.27351227])

In [65]:
model3.fit(X,y)
chech2=model3.predict(X_test)
chech2

0:	learn: 0.1829429	total: 3.35ms	remaining: 30.2ms
1:	learn: 0.1729038	total: 6.67ms	remaining: 26.7ms
2:	learn: 0.1644941	total: 9.96ms	remaining: 23.2ms
3:	learn: 0.1571153	total: 13.1ms	remaining: 19.6ms
4:	learn: 0.1510166	total: 16.2ms	remaining: 16.2ms
5:	learn: 0.1453628	total: 19.5ms	remaining: 13ms
6:	learn: 0.1406357	total: 22.4ms	remaining: 9.62ms
7:	learn: 0.1363435	total: 25.3ms	remaining: 6.33ms
8:	learn: 0.1327992	total: 28.1ms	remaining: 3.12ms
9:	learn: 0.1296084	total: 31ms	remaining: 0us

array([0.24638204, 0.3140066 , 0.51967467, ..., 0.44921452, 0.27635292,
       0.45545899])

In [67]:
sub.head()

            ID  Target
0  ID_AAcismbB       0
1  ID_AAeBMsji       0
2  ID_AAjFMjzy       0
3  ID_AAmMOEEC       0
4  ID_ABguzDxp       0

In [72]:
ss = sub.copy()
ss.Target = chech2
submission = pd.DataFrame({"ID": ss.ID, "Target":ss.Target })
submission.to_csv('My_First_Submission.csv', index=False)
submission

               ID    Target
0     ID_AAcismbB  0.246382
1     ID_AAeBMsji  0.314007
2     ID_AAjFMjzy  0.519675
3     ID_AAmMOEEC  0.379753
4     ID_ABguzDxp  0.277793
...           ...       ...
7189  ID_zxzKJCMI  0.278562
7190  ID_zyBrpgRp  0.339227
7191  ID_zyMafcYq  0.449215
7192  ID_zyfMsHMG  0.276353
7193  ID_zytUOqJv  0.455459

[7194 rows x 2 columns]