In [208]:
import os
import pandas as pd
import  numpy as np
import matplotlib as plt
%matplotlib inline
import warnings
 warnings.simplefilter("ignore")

IndentationError: unexpected indent (<ipython-input-208-49d3ddfb8218>, line 7)

In [ ]:
df_Train = pd.read_csv("Train.csv")
df_Test  = pd.read_csv("Test.csv")
sub= pd.read_csv("SampleSubmission.csv")

# UNDERSTANDING DATA

In [ ]:
df_Train.head()

In [209]:
df_Test.head()

,ID,country,year,urban_or_rural,ghsl_water_surface,ghsl_built_pre_1975,ghsl_built_1975_to_1990,ghsl_built_1990_to_2000,ghsl_built_2000_to_2014,ghsl_not_built_up,ghsl_pop_density,landcover_crops_fraction,landcover_urban_fraction,landcover_water_permanent_10km_fraction,landcover_water_seasonal_10km_fraction,nighttime_lights,dist_to_capital,dist_to_shoreline
0,ID_AAcismbB,3,2007,0,0.000000,0.000000,0.000000,0.000523,0.000131,0.999347,0.660758,0.990942,0.132264,0.069055,0.032627,0.000000,1249.294720,1364.592100
1,ID_AAeBMsji,3,2007,1,0.000000,0.004239,0.000238,0.001227,0.002860,0.991437,6.441547,5.461365,0.452400,0.000000,0.000000,0.000000,821.019579,1046.028681
2,ID_AAjFMjzy,4,2011,1,0.007359,0.525682,0.132795,0.095416,0.042375,0.196373,587.516458,2.881811,87.387991,3.248483,3.950374,60.070041,3.620455,906.057334
3,ID_AAmMOEEC,2,2010,1,0.000000,0.000089,0.000036,0.001519,0.001358,0.996997,35.141762,33.878927,4.166437,0.000000,0.130727,1.333999,109.493969,775.139189
4,ID_ABguzDxp,5,2007,0,0.000000,0.000138,0.000623,0.000615,0.002961,0.995663,3.442449,33.491994,3.437129,0.133563,0.128997,0.502203,133.643319,835.591501

In [210]:
df_Train.describe().T

,count,mean,std,min,25%,50%,75%,max
country,21454.0,8.644262,4.636224,0.000000,5.000000,8.000000,12.000000,17.000000
year,21454.0,2010.060874,4.799579,1994.000000,2008.000000,2011.000000,2014.000000,2016.000000
urban_or_rural,21454.0,0.344598,0.475248,0.000000,0.000000,0.000000,1.000000,1.000000
ghsl_water_surface,21454.0,0.028259,0.097490,0.000000,0.000000,0.000000,0.000000,0.969956
ghsl_built_pre_1975,21454.0,0.038222,0.113562,0.000000,0.000000,0.000198,0.007987,0.877116
ghsl_built_1975_to_1990,21454.0,0.028644,0.077367,0.000000,0.000000,0.000709,0.009868,0.685010
ghsl_built_1990_to_2000,21454.0,0.012689,0.032745,0.000000,0.000043,0.001001,0.008128,0.515534
ghsl_built_2000_to_2014,21454.0,0.018386,0.040421,0.000000,0.000124,0.001871,0.014936,0.649159
ghsl_not_built_up,21454.0,0.873800,0.239294,0.000859,0.897867,0.991919,0.999532,1.000000
ghsl_pop_density,21454.0,95.756775,209.704761,0.000000,3.848533,17.632672,63.225683,1741.256516
landcover_crops_fraction,21454.0,21.034265,16.751106,0.000000,5.610515,18.509291,33.590293,80.064918
landcover_urban_fraction,21454.0,13.999061,23.715485,0.000000,0.798841,2.770159,12.621501,98.784092
landcover_water_permanent_10km_fraction,21454.0,1.486849,6.550171,0.000000,0.000000,0.000516,0.152364,99.164018
landcover_water_seasonal_10km_fraction,21454.0,0.714891,2.383701,0.000000,0.001325,0.029151,0.381969,56.201637
nighttime_lights,21454.0,8.506543,21.090378,0.000000,0.000000,0.137333,4.830194,382.932769
dist_to_capital,21454.0,289.722268,238.811778,0.105306,115.890873,256.736472,401.153071,1897.351575
dist_to_shoreline,21454.0,402.608539,321.517285,0.112080,126.379463,327.271973,643.910675,1769.523906

# PERFORMING STATISTICAL ANALYSIS USING PANDAS PROFILING

In [211]:
#import pandas_profiling as pp

In [212]:
#profile = pp.ProfileReport(df_Train, title ="Economic Well-Being Prediction Challenge")
#profile

In [213]:
df_Train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21454 entries, 0 to 21453
Data columns (total 17 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   country                                  21454 non-null  int64
 1   year                                     21454 non-null  int64
 2   urban_or_rural                           21454 non-null  int64
 3   ghsl_water_surface                       21454 non-null  float64
 4   ghsl_built_pre_1975                      21454 non-null  float64
 5   ghsl_built_1975_to_1990                  21454 non-null  float64
 6   ghsl_built_1990_to_2000                  21454 non-null  float64
 7   ghsl_built_2000_to_2014                  21454 non-null  float64
 8   ghsl_not_built_up                        21454 non-null  float64
 9   ghsl_pop_density                         21454 non-null  float64
 10  landcover_crops_fraction                 21454 non-null  float64
 11  landcover_urban_fraction                 21454 non-null  float64
 12  landcover_water_permanent_10km_fraction  21454 non-null  float64
 13  landcover_water_seasonal_10km_fraction   21454 non-null  float64
 14  nighttime_lights                         21454 non-null  float64
 15  dist_to_capital                          21454 non-null  float64
 16  dist_to_shoreline                        21454 non-null  float64
dtypes: float64(14), int64(3)
memory usage: 2.8 MB

In [214]:
df_Train.shape

(21454, 17)

In [215]:
df_Test.shape

(7194, 18)

CHECKING THE TARGET

In [216]:
#Target_count = df_Train.groupby("Target").size()
#Target_count

In [217]:
df_Train.skew().T

country                                    0.026767
year                                      -1.208174
urban_or_rural                             0.654045
ghsl_water_surface                         4.462055
ghsl_built_pre_1975                        4.060007
ghsl_built_1975_to_1990                    3.829905
ghsl_built_1990_to_2000                    5.544228
ghsl_built_2000_to_2014                    3.985801
ghsl_not_built_up                         -2.134893
ghsl_pop_density                           3.605561
landcover_crops_fraction                   0.562865
landcover_urban_fraction                   2.016126
landcover_water_permanent_10km_fraction    7.653752
landcover_water_seasonal_10km_fraction     8.147797
nighttime_lights                           3.700020
dist_to_capital                            1.971310
dist_to_shoreline                          0.624904
dtype: float64

As rule of thumb, skewness can be interpreted like this
                          Skewness
Fairly Symmetrica    -0.5 to 0.5
Moderate Skewed        -0.5 to -1.0 and 0.5 to 1.0
Highly Skewed        < -1.0 and > 1.0

# PRE-PROCESSING OF DATA

In [218]:
df_Train.isnull().sum().any(),df_Test.isnull().sum().any()

(False, False)

In [219]:
df_Train.duplicated().sum().any(),df_Test.duplicated().sum().any()

(True, False)

In [220]:
from sklearn.preprocessing import LabelEncoder

In [221]:
# categorical data conversation for Train
le = LabelEncoder()
df_Train["country"] = le.fit_transform(df_Train["country"])
df_Train["urban_or_rural"] = le.fit_transform(df_Train["urban_or_rural"])

# categorical data conversation for Test
df_Test["country"] = le.fit_transform(df_Test["country"])
df_Test["urban_or_rural"] = le.fit_transform(df_Test["urban_or_rural"])

In [222]:
df_Train.head()

,country,year,urban_or_rural,ghsl_water_surface,ghsl_built_pre_1975,ghsl_built_1975_to_1990,ghsl_built_1990_to_2000,ghsl_built_2000_to_2014,ghsl_not_built_up,ghsl_pop_density,landcover_crops_fraction,landcover_urban_fraction,landcover_water_permanent_10km_fraction,landcover_water_seasonal_10km_fraction,nighttime_lights,dist_to_capital,dist_to_shoreline
0,3,2016,0,0.0,0.000000,0.000000,0.000055,0.000536,0.999408,12.146134,25.489659,0.879484,0.000000,0.000000,0.000000,278.788451,769.338378
1,3,2005,0,0.0,0.000000,0.000110,0.000000,0.000018,0.999872,113.806716,64.136053,0.601427,0.000000,0.005427,0.000000,200.986978,337.135243
2,10,2009,0,0.0,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,4.400096,0.131900,0.000000,0.003078,0.000000,642.594208,169.913773
3,8,2015,0,0.0,0.000141,0.000181,0.000254,0.000228,0.999195,5.213320,25.379371,2.017136,11.293841,0.131035,0.000000,365.349451,613.591610
4,5,2012,1,0.0,0.011649,0.017560,0.017383,0.099875,0.853533,31.734661,5.081620,22.815984,0.005047,0.130475,1.461894,222.867189,192.926363

In [223]:
# droping Target
df_Train.drop(["ID","Target"], 1, inplace= True)

KeyError: "['ID' 'Target'] not found in axis"

In [ ]:
df_Train.info()

In [ ]:
# creating the X of test set
test = df_Test.drop(["ID"],1)

In [ ]:
# EVALUATING THE PERFORMANCE OF THE MODEL
from sklearn.model_selection import train_test_split
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score

In [ ]:
array = df_Train.values
X = array[:,0:16]
y = array[:,16]

In [ ]:
folds =KFold(n_splits=10, random_state=2020, shuffle= True)

In [ ]:
from sklearn.linear_model import LogisticRegression

In [ ]:
model = LogisticRegression()
scoring = "accuracy"
results = cross_val_score(model, X, y, cv=folds, scoring =scoring )
results.mean()